import pdfMake from 'pdfmake/build/pdfmake';
// @ts-ignore - pdfmake fonts structure
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
import { TDocumentDefinitions, Content } from 'pdfmake/interfaces';
import { ReportData } from '../schemas/report.schema';

// Set up fonts
// @ts-ignore
pdfMake.vfs = pdfFonts.pdfMake ? pdfFonts.pdfMake.vfs : pdfFonts;

/**
 * Generates a PDF document from report data
 */
export async function generatePDFReport(reportData: ReportData): Promise<Buffer> {
  const docDefinition: TDocumentDefinitions = {
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60],
    
    header: (currentPage, pageCount) => {
      return {
        text: `${reportData.reportType.replace(/_/g, ' ')} Report | Page ${currentPage} of ${pageCount}`,
        alignment: 'center',
        margin: [0, 20, 0, 0],
        fontSize: 10,
        color: '#666666'
      };
    },
    
    footer: (currentPage, pageCount) => {
      return {
        columns: [
          {
            text: `Generated by PocketTogether on ${reportData.generatedAt.toLocaleDateString()}`,
            fontSize: 8,
            color: '#888888',
            margin: [40, 10, 0, 0]
          },
          {
            text: `${currentPage}/${pageCount}`,
            alignment: 'right',
            fontSize: 8,
            color: '#888888',
            margin: [0, 10, 40, 0]
          }
        ]
      };
    },
    
    content: buildPDFContent(reportData),
    
    styles: {
      header: {
        fontSize: 22,
        bold: true,
        margin: [0, 0, 0, 10]
      },
      subheader: {
        fontSize: 16,
        bold: true,
        margin: [0, 15, 0, 8]
      },
      metadata: {
        fontSize: 10,
        color: '#666666',
        margin: [0, 2, 0, 2]
      },
      summaryCard: {
        fontSize: 12,
        margin: [0, 5, 0, 5]
      },
      tableHeader: {
        bold: true,
        fontSize: 11,
        fillColor: '#E5E7EB',
        margin: [0, 5, 0, 5]
      }
    }
  };
  
  return new Promise((resolve, reject) => {
    try {
      const pdfDoc = pdfMake.createPdf(docDefinition);
      pdfDoc.getBuffer((buffer: Buffer) => {
        resolve(buffer);
      });
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Build PDF content based on report data
 */
function buildPDFContent(reportData: ReportData): Content[] {
  const content: Content[] = [];
  
  // Title
  content.push({
    text: `${reportData.reportType.replace(/_/g, ' ')} REPORT`,
    style: 'header',
    alignment: 'center'
  });
  
  // Metadata
  content.push({
    text: [
      { text: 'Household: ', bold: true },
      { text: reportData.householdName }
    ],
    style: 'metadata'
  });
  
  content.push({
    text: [
      { text: 'Date Range: ', bold: true },
      { text: `${reportData.dateRange.start} to ${reportData.dateRange.end}` }
    ],
    style: 'metadata'
  });
  
  content.push({
    text: [
      { text: 'Generated: ', bold: true },
      { text: reportData.generatedAt.toLocaleString() }
    ],
    style: 'metadata',
    margin: [0, 2, 0, 15]
  });
  
  // Summary Cards
  content.push({
    text: 'SUMMARY',
    style: 'subheader'
  });
  
  content.push({
    columns: [
      {
        stack: [
          { text: 'Total Income', fontSize: 10, color: '#666666' },
          { text: `₹${formatNumber(reportData.summary.totalIncome)}`, fontSize: 14, bold: true, color: '#10B981', margin: [0, 5, 0, 0] }
        ],
        width: '33%'
      },
      {
        stack: [
          { text: 'Total Expense', fontSize: 10, color: '#666666' },
          { text: `₹${formatNumber(reportData.summary.totalExpense)}`, fontSize: 14, bold: true, color: '#EF4444', margin: [0, 5, 0, 0] }
        ],
        width: '33%'
      },
      {
        stack: [
          { text: 'Net Savings', fontSize: 10, color: '#666666' },
          { text: `₹${formatNumber(reportData.summary.netSavings)}`, fontSize: 14, bold: true, margin: [0, 5, 0, 0] }
        ],
        width: '34%'
      }
    ],
    margin: [0, 0, 0, 20]
  });
  
  // Add specific content based on report type
  if (reportData.transactions && reportData.transactions.length > 0) {
    addTransactionsTable(content, reportData);
  }
  
  if (reportData.categoryBreakdown && reportData.categoryBreakdown.length > 0) {
    addCategoryBreakdownTable(content, reportData);
  }
  
  if (reportData.accountBreakdown && reportData.accountBreakdown.length > 0) {
    addAccountBreakdownTable(content, reportData);
  }
  
  if (reportData.loanSchedule) {
    addLoanScheduleTable(content, reportData);
  }
  
  if (reportData.creditCardStatements) {
    addCreditCardStatementsTable(content, reportData);
  }
  
  if (reportData.budgetComparison && reportData.budgetComparison.length > 0) {
    addBudgetComparisonTable(content, reportData);
  }
  
  if (reportData.monthlyTrends && reportData.monthlyTrends.length > 0) {
    addMonthlyTrendsTable(content, reportData);
  }
  
  return content;
}

/**
 * Add Transactions Table
 */
function addTransactionsTable(content: Content[], reportData: ReportData) {
  content.push({
    text: 'TRANSACTIONS',
    style: 'subheader',
    pageBreak: 'before'
  });
  
  const tableBody: any[] = [
    [
      { text: 'Date', style: 'tableHeader' },
      { text: 'Description', style: 'tableHeader' },
      { text: 'Category', style: 'tableHeader' },
      { text: 'Amount', style: 'tableHeader', alignment: 'right' }
    ]
  ];
  
  // Limit to first 50 transactions for PDF readability
  const transactions = reportData.transactions!.slice(0, 50);
  
  transactions.forEach(txn => {
    tableBody.push([
      { text: new Date(txn.date).toLocaleDateString(), fontSize: 9 },
      { text: txn.description.substring(0, 30), fontSize: 9 },
      { text: txn.category, fontSize: 9 },
      { text: `₹${formatNumber(txn.amount)}`, fontSize: 9, alignment: 'right' }
    ]);
  });
  
  if (reportData.transactions!.length > 50) {
    tableBody.push([
      { text: `... and ${reportData.transactions!.length - 50} more transactions`, colSpan: 4, italics: true, fontSize: 9, color: '#666666' },
      {}, {}, {}
    ]);
  }
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['auto', '*', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number) => {
        return rowIndex === 0 ? '#E5E7EB' : (rowIndex % 2 === 0 ? '#F9FAFB' : null);
      }
    }
  });
}

/**
 * Add Category Breakdown Table
 */
function addCategoryBreakdownTable(content: Content[], reportData: ReportData) {
  content.push({
    text: 'CATEGORY BREAKDOWN',
    style: 'subheader',
    pageBreak: 'before'
  });
  
  const tableBody: any[] = [
    [
      { text: 'Category', style: 'tableHeader' },
      { text: 'Amount', style: 'tableHeader', alignment: 'right' },
      { text: 'Count', style: 'tableHeader', alignment: 'right' },
      { text: '%', style: 'tableHeader', alignment: 'right' }
    ]
  ];
  
  reportData.categoryBreakdown!.forEach(cat => {
    tableBody.push([
      { text: cat.categoryName, fontSize: 10 },
      { text: `₹${formatNumber(cat.amount)}`, fontSize: 10, alignment: 'right' },
      { text: cat.count.toString(), fontSize: 10, alignment: 'right' },
      { text: `${cat.percentage}%`, fontSize: 10, alignment: 'right' }
    ]);
  });
  
  // Total row
  const total = reportData.categoryBreakdown!.reduce((sum, cat) => sum + cat.amount, 0);
  tableBody.push([
    { text: 'TOTAL', bold: true, fontSize: 10 },
    { text: `₹${formatNumber(total)}`, bold: true, fontSize: 10, alignment: 'right' },
    { text: '', fontSize: 10 },
    { text: '100%', bold: true, fontSize: 10, alignment: 'right' }
  ]);
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['*', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number, node: any) => {
        if (rowIndex === 0) return '#E5E7EB';
        if (rowIndex === node.table.body.length - 1) return null; // No fill for total row
        return rowIndex % 2 === 0 ? '#F9FAFB' : null;
      }
    }
  });
}

/**
 * Add Account Breakdown Table
 */
function addAccountBreakdownTable(content: Content[], reportData: ReportData) {
  content.push({
    text: 'ACCOUNT BREAKDOWN',
    style: 'subheader'
  });
  
  const tableBody: any[] = [
    [
      { text: 'Account', style: 'tableHeader' },
      { text: 'Income', style: 'tableHeader', alignment: 'right' },
      { text: 'Expense', style: 'tableHeader', alignment: 'right' },
      { text: 'Balance', style: 'tableHeader', alignment: 'right' }
    ]
  ];
  
  reportData.accountBreakdown!.forEach(acc => {
    tableBody.push([
      { text: acc.accountName, fontSize: 10 },
      { text: `₹${formatNumber(acc.income)}`, fontSize: 10, alignment: 'right' },
      { text: `₹${formatNumber(acc.expense)}`, fontSize: 10, alignment: 'right' },
      { text: `₹${formatNumber(acc.balance)}`, fontSize: 10, alignment: 'right', bold: true }
    ]);
  });
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['*', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number) => {
        return rowIndex === 0 ? '#E5E7EB' : (rowIndex % 2 === 0 ? '#F9FAFB' : null);
      }
    }
  });
}

/**
 * Add Loan Schedule Table
 */
function addLoanScheduleTable(content: Content[], reportData: ReportData) {
  const loan = reportData.loanSchedule!;
  
  content.push({
    text: 'LOAN SCHEDULE',
    style: 'subheader',
    pageBreak: 'before'
  });
  
  content.push({
    text: [
      { text: 'Loan: ', bold: true },
      { text: loan.loanName }
    ],
    margin: [0, 0, 0, 5]
  });
  
  content.push({
    text: [
      { text: 'Outstanding Principal: ', bold: true },
      { text: `₹${formatNumber(loan.outstandingPrincipal)}` }
    ],
    margin: [0, 0, 0, 10]
  });
  
  const tableBody: any[] = [
    [
      { text: 'EMI #', style: 'tableHeader' },
      { text: 'Due Date', style: 'tableHeader' },
      { text: 'Principal', style: 'tableHeader', alignment: 'right' },
      { text: 'Interest', style: 'tableHeader', alignment: 'right' },
      { text: 'Total', style: 'tableHeader', alignment: 'right' },
      { text: 'Status', style: 'tableHeader' }
    ]
  ];
  
  loan.emis.forEach(emi => {
    tableBody.push([
      { text: emi.emiNumber.toString(), fontSize: 9 },
      { text: new Date(emi.dueDate).toLocaleDateString(), fontSize: 9 },
      { text: `₹${formatNumber(emi.principalComponent)}`, fontSize: 9, alignment: 'right' },
      { text: `₹${formatNumber(emi.interestComponent)}`, fontSize: 9, alignment: 'right' },
      { text: `₹${formatNumber(emi.totalAmount)}`, fontSize: 9, alignment: 'right', bold: true },
      { text: emi.status, fontSize: 9 }
    ]);
  });
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['auto', 'auto', 'auto', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number) => {
        return rowIndex === 0 ? '#E5E7EB' : (rowIndex % 2 === 0 ? '#F9FAFB' : null);
      }
    },
    fontSize: 9
  });
}

/**
 * Add Credit Card Statements Table
 */
function addCreditCardStatementsTable(content: Content[], reportData: ReportData) {
  const card = reportData.creditCardStatements!;
  
  content.push({
    text: 'CREDIT CARD STATEMENTS',
    style: 'subheader',
    pageBreak: 'before'
  });
  
  content.push({
    text: [
      { text: 'Card: ', bold: true },
      { text: card.cardName }
    ],
    margin: [0, 0, 0, 5]
  });
  
  content.push({
    text: [
      { text: 'Outstanding: ', bold: true },
      { text: `₹${formatNumber(card.outstandingAmount)}` }
    ],
    margin: [0, 0, 0, 10]
  });
  
  const tableBody: any[] = [
    [
      { text: 'Statement Date', style: 'tableHeader' },
      { text: 'Spends', style: 'tableHeader', alignment: 'right' },
      { text: 'Payments', style: 'tableHeader', alignment: 'right' },
      { text: 'Closing Bal.', style: 'tableHeader', alignment: 'right' },
      { text: 'Status', style: 'tableHeader' }
    ]
  ];
  
  card.statements.forEach(stmt => {
    tableBody.push([
      { text: new Date(stmt.statementDate).toLocaleDateString(), fontSize: 9 },
      { text: `₹${formatNumber(stmt.totalSpends)}`, fontSize: 9, alignment: 'right' },
      { text: `₹${formatNumber(stmt.totalPayments)}`, fontSize: 9, alignment: 'right' },
      { text: `₹${formatNumber(stmt.closingBalance)}`, fontSize: 9, alignment: 'right', bold: true },
      { text: stmt.status, fontSize: 9 }
    ]);
  });
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['auto', 'auto', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number) => {
        return rowIndex === 0 ? '#E5E7EB' : (rowIndex % 2 === 0 ? '#F9FAFB' : null);
      }
    }
  });
}

/**
 * Add Budget Comparison Table
 */
function addBudgetComparisonTable(content: Content[], reportData: ReportData) {
  content.push({
    text: 'BUDGET VS ACTUAL',
    style: 'subheader'
  });
  
  const tableBody: any[] = [
    [
      { text: 'Category', style: 'tableHeader' },
      { text: 'Budgeted', style: 'tableHeader', alignment: 'right' },
      { text: 'Actual', style: 'tableHeader', alignment: 'right' },
      { text: 'Difference', style: 'tableHeader', alignment: 'right' },
      { text: '% Used', style: 'tableHeader', alignment: 'right' }
    ]
  ];
  
  reportData.budgetComparison!.forEach(item => {
    tableBody.push([
      { text: item.categoryName, fontSize: 10 },
      { text: `₹${formatNumber(item.budgeted)}`, fontSize: 10, alignment: 'right' },
      { text: `₹${formatNumber(item.actual)}`, fontSize: 10, alignment: 'right' },
      { 
        text: `₹${formatNumber(item.difference)}`, 
        fontSize: 10, 
        alignment: 'right',
        color: item.difference < 0 ? '#EF4444' : '#10B981'
      },
      { text: `${item.percentageUsed}%`, fontSize: 10, alignment: 'right' }
    ]);
  });
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['*', 'auto', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number) => {
        return rowIndex === 0 ? '#E5E7EB' : (rowIndex % 2 === 0 ? '#F9FAFB' : null);
      }
    }
  });
}

/**
 * Add Monthly Trends Table
 */
function addMonthlyTrendsTable(content: Content[], reportData: ReportData) {
  content.push({
    text: 'MONTHLY TRENDS',
    style: 'subheader',
    pageBreak: 'before'
  });
  
  const tableBody: any[] = [
    [
      { text: 'Month', style: 'tableHeader' },
      { text: 'Income', style: 'tableHeader', alignment: 'right' },
      { text: 'Expense', style: 'tableHeader', alignment: 'right' },
      { text: 'Net Savings', style: 'tableHeader', alignment: 'right' }
    ]
  ];
  
  reportData.monthlyTrends!.forEach(trend => {
    tableBody.push([
      { text: trend.month, fontSize: 10 },
      { text: `₹${formatNumber(trend.income)}`, fontSize: 10, alignment: 'right' },
      { text: `₹${formatNumber(trend.expense)}`, fontSize: 10, alignment: 'right' },
      { text: `₹${formatNumber(trend.netSavings)}`, fontSize: 10, alignment: 'right', bold: true }
    ]);
  });
  
  // Total row
  tableBody.push([
    { text: 'TOTAL', bold: true, fontSize: 10 },
    { text: `₹${formatNumber(reportData.summary.totalIncome)}`, bold: true, fontSize: 10, alignment: 'right' },
    { text: `₹${formatNumber(reportData.summary.totalExpense)}`, bold: true, fontSize: 10, alignment: 'right' },
    { text: `₹${formatNumber(reportData.summary.netSavings)}`, bold: true, fontSize: 10, alignment: 'right' }
  ]);
  
  content.push({
    table: {
      headerRows: 1,
      widths: ['*', 'auto', 'auto', 'auto'],
      body: tableBody
    },
    layout: {
      fillColor: (rowIndex: number, node: any) => {
        if (rowIndex === 0) return '#E5E7EB';
        if (rowIndex === node.table.body.length - 1) return null;
        return rowIndex % 2 === 0 ? '#F9FAFB' : null;
      }
    }
  });
}

/**
 * Format number with commas
 */
function formatNumber(num: number): string {
  return num.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}
